# Home Assistant Configuration for XCC Integration Testing

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable the recorder
recorder:
  db_url: sqlite:////config/home-assistant_v2.db

# Enable logging
logger:
  default: info
  logs:
    homeassistant.components.xcc: debug
    custom_components.xcc: debug

# MQTT Configuration
mqtt:
  broker: mqtt-dev
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

# HTTP Configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12

# Enable developer tools
developer:

# Example automation for testing
automation:
  - alias: "XCC Temperature Alert"
    trigger:
      platform: numeric_state
      entity_id: sensor.xcc_outdoor_temperature
      below: 0
    action:
      service: persistent_notification.create
      data:
        title: "XCC Alert"
        message: "Outdoor temperature is below freezing!"

# Example sensor template
template:
  - sensor:
      - name: "XCC Efficiency Percentage"
        unit_of_measurement: "%"
        state: "{{ (states('sensor.xcc_efficiency_cop') | float * 100 / 6) | round(1) }}"
        availability: "{{ states('sensor.xcc_efficiency_cop') not in ['unknown', 'unavailable'] }}"
